name: simple_note
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+11

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  table_calendar: ^3.1.1
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.2.1
  substring_highlight: ^1.0.33
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.2.0
  timelines: ^0.1.0
  flutter_email_sender: ^6.0.3
  google_mobile_ads: ^5.1.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons64.png

  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
#          weight: 100
#          style: italic
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
    - family: D2CodingRegular
      fonts:
        - asset: assets/fonts/d2coding/D2Coding-Ver1.3.2-20180524.ttf
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/nanum_myeongjo/NanumMyeongjo.ttf
    - family: NanumBrush
      fonts:
        - asset: assets/fonts/nanum_brush/NanumBrush.ttf
    - family: nanum_pen
      fonts:
        - asset: assets/fonts/nanum_pen/NanumPen.ttf
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/NanumSquareNeo/NanumSquareNeo-bRg.ttf


flutter_native_splash:
  color: "#FFFFFF" # background color
  image: assets/icons64.png # 추가할 이미지 파일 경로를 추가
  android: true
  ios: true
  web: fa


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons64.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
